### ISSUE TITLE
WCF

### ISSUE THREAD

**Issue by iasimin** [Tiberiu-Cocei/TSP.NET#1]
Acest cod nu functioneaza.
Trimiteti-mi o captura de ecran.

**Comment by Tiberiu-Cocei** [comment]
![Untitled](https://user-images.githubusercontent.com/48532599/77564399-5283b080-6ecb-11ea-894b-29e844143b2a.png)

**Comment by iasimin** [comment]
In HostWCF connectionString contine numele calculatorului meu.
Ati inteles?
Codul nu are cum sa functioneze. 
Sunteti de acord?

**Comment by Tiberiu-Cocei** [comment]
Am inteles, am schimbat connection string-ul si am dat push la modificare.
